name: BartPOIBVT

on:
  workflow_dispatch:
  pull_request:


env:
  PROJECT_PATH: './apis/poi/web/poi.csproj'
  TEST_PATH: './apis/poi/tests/UnitTests/UnitTests.csproj'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_PATH }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.TEST_PATH }}
