# This is a basic workflow that is manually triggered

name: Manual workflow

env:
  APPLICATIONPATH: Application
  DOCKERFILEPATH: "apis/poi/web"
  REGISTRYNAME: "openhackwf422ai1acr"
  IMAGENAME: "devopsoh/api-poi"
  STAGINGSLOT: "https://openhackwf422ai1poi-staging.azurewebsites.net/api/healthcheck/poi"
  PRODUCTIONSLOT: "https://openhackwf422ai1poi.azurewebsites.net/api/healthcheck/poi"

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  curlcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: enflo/curl-action@v1.2
      with:
        curl: ${{ env.STAGINGSLOT }}

    - name: Set selected color
      run: echo '::set-output name=SELECTED_COLOR::green'
      id: random-color-generator
    - name: Get color
      run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
