# This is a basic workflow that is manually triggered

name: Manual workflow

env:
  APPLICATIONPATH: Application
  DOCKERFILEPATH: "apis/poi/web"
  REGISTRYNAME: "openhackwf422ai1acr"
  IMAGENAME: "devopsoh/api-poi"
  STAGINGSLOT: "https://openhackwf422ai1poi-staging.azurewebsites.net/api/healthcheck/poi"
  PRODUCTIONSLOT: "https://openhackwf422ai1poi.azurewebsites.net/api/healthcheck/poi"
  RETURN_VAL: "test"

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  curlcheck:
    runs-on: ubuntu-latest
    
    steps:
    - name: thischeck
      id: curlcheck2
      run: curl ${{ env.STAGINGSLOT }} >> RETURN_VAL

    - name: thischeck2
      id: curlcheck3
      run: '%RETURN_VAL = curl ${{ env.STAGINGSLOT }}'

    - name: Show result
      run: echo "The curl result is ${{ %RETURN_VAL }}"
      
    - name: Show result
      run: echo "The curl result is ${{ steps.curlcheck3.outputs.THIS_VAL }}"
      
    - name: Show result
      run: echo "The curl result is ${{ steps.curlcheck3.outputs.THIS_VAL }}"
      

      
