# This is a basic workflow that is manually triggered

name: Manual workflow

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  APPLICATIONPATH: Application
  DOCKERFILEPATH: "apis/poi/web"
  REGISTRYNAME: "openhackwf422ai1acr"
  IMAGENAME: "devopsoh/api-poi"
  STAGINGSLOT: "https://openhackwf422ai1poi-staging.azurewebsites.net/api/healthcheck/poi"
  PRODUCTIONSLOT: "https://openhackwf422ai1poi.azurewebsites.net/api/healthcheck/poi"
  RETURN_VAL: "test"
  

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  curlcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Validate Stage Deployment
      run: |
        pwd
        ls -la
        chmod +x stg_poihttp.sh
        ./stg_poihttp.sh ${{env.STAGINGSLOT}} Healthy
        
    - name: stage validation result
      run: "echo Status is: ${{env.SITESTATUS}}"

#if env.SITESTATUS==true, do a slot swap and check the production URL
    - name : check result
      if: ${{env.SITESTATUS}}==true
      run: echo ${{ env.SITESTATUS }}

    - name : check result
      if: ${{env.SITESTATUS}} == false
      run: echo ${{ env.SITESTATUS }}
      
    - name: Validate Prod Deployment
      run: |
        pwd
        ls -la
        chmod +x stg_poihttp.sh
        ./stg_poihttp.sh ${{env.PRODUCTIONSLOT}} Healthy
        
    - name: stage validation result
      run: "echo Status is: ${{env.SITESTATUS}}"
    

      
